### ISSUE TITLE
Need advice on how to change my current dspam setup to dspam-milter way.

### ISSUE THREAD

**Issue by pvanthony** [mk-fg/dspam-milter#1]
Hi,

Currently using postfix and dspam. The dspam is setup only to add [SPAM] on the subject header. Very similar to your setup of never rejecting emails, which I like.

When dspam makes a mistake, the email is sent to spam@example.com or notspam@example.com

Would like to change the current setup to use dspam-milter. May I have some advice on how to change the setup to use dspam-milter?

For the incoming emails, I understand the setup mentioned in the readme.
smtpd_milters = unix:/tmp/dspam_milter.sock 
non_smtpd_milters = unix:/tmp/dspam_milter.sock

How about the training setup when dspam gets it wrong? Would it be the same as the current setup?

The current setup is as follows.

For incoming emails. (main.cf)
smtpd_recipient_restrictions =  check_policy_service inet:127.0.0.1:10031,
                                permit_mynetworks,
                                permit_sasl_authenticated,
                                ...
                                ...
                                check_client_access pcre:/etc/postfix/dspam_incoming

dspam_incoming file has,
/./	FILTER lmtp:unix:/var/run/dspam/dspam.sock

then,
spam_dspam_destination_recipient_limit = 1
notspam_dspam_destination_recipient_limit = 1

For reclassification when there is an error by dspam. (master.cf)
#This is for mail coming back from dspam
127.0.0.1:10028 inet    n   -   -   -   -   smtpd
        -o content_filter=
        -o receive_override_options=no_unknown_recipient_checks,no_header_body_checks
        -o smtpd_helo_restrictions=
        -o smtpd_client_restrictions=
        -o smtpd_sender_restrictions=
        -o smtpd_recipient_restrictions=permit_mynetworks,reject
        -o mynetworks=127.0.0.0/8
        -o smtpd_authorized_xforward_hosts=127.0.0.0/8
        -o smtpd_milters=
#end dspam

#handle dspam retrain
#This path is used when a user sends in a piece of mail and wants to classify it as SPAM
spam_dspam           unix   -   n   n   -   -   pipe
  flags=Rhq user=vmail argv=/usr/bin/dspam --user vmail --class=spam --source=error

#This path is used when a user sends in a piece of mail and wants to classify it as INNOCENT
notspam_dspam        unix   -   n   n   -   -   pipe
  flags=Rhq user=vmail argv=/usr/bin/dspam --user vmail --class=innocent --source=error

**Comment by mk-fg** [comment]
Hi,

> Would like to change the current setup to use dspam-milter. May I have some advice on how to change the setup to use dspam-milter?

Note: I haven't really used the thing for a few (I think 2-3) years now, as after a while, I've found resource drain of dspam (using pgsql as a backend) a bit too much for very little need for it that there was.
(iirc it was cpu usage of pgsql once db got big enough, given very limited hw power, but it probably could've been trimmed/compacted/optimized greatly, given the inclination)

Things aren't changing that fast in the world of email though (sendmail milters in 2017!), so it probably works just fine, and should be safe to try in config, as in the worst-case mail will be delayed until milter is disabled again (if not working).


> How about the training setup when dspam gets it wrong? Would it be the same as the current setup?

From a brief look - yeah, I think your current setup for these two recipient-paths should work just fine.

I haven't tinkered with postfix setups in a while, but fairly sure only downside there might be lost spam/ham information if running that command fails for some reason (e.g. os limits, segfault, stuff like that).

Didn't add option to use milter for such paths (which should avoid issue above), as I had train-script running from crontab using specific maildir folders, but it shouldn't be hard either - just passing extra options to dspamc here: https://github.com/mk-fg/dspam-milter/blob/c39db13/dspam-milter.py#L142

I'll add a cli option for passing whatever arguments to dspamc binary there, I guess.

**Comment by mk-fg** [comment]
Should be possible to use separate milter instance for these paths, started with e.g. `./dspam-milter.py --dspam-opts '--class=spam --source=error'` (and feeding mail to /dev/null after that), as of 43d933ec64

As noted, don't actually use the thing myself though, so didn't really test this change (and pointless dependency dropped in a50ae14), but it's rather trivial so should probably work.
Would appreciate if you'd report any errors/bugs there, if you'll end up trying the thing out.

**Comment by pvanthony** [comment]
On 07/01/2017 03:29, Mike Kazantsev wrote:
> Should be possible to use separate milter instance for these paths,
> started with e.g. |./dspam-milter.py --dspam-opts '--class=spam
> --source=error'| (and feeding mail to /dev/null after that), as of
> 43d933e
> <https://github.com/mk-fg/dspam-milter/commit/43d933ec640f8d833f8a55f7955d8ed3c5a51083>

Thank you very much for making the changes in the code for my use. I do 
appreciate it very much.

Sorry for the delay in replying. I only do test on the server on weekends.

> As noted, don't actually use the thing myself though, so didn't really
> test this change (and pointless dependency dropped in a50ae14
> <https://github.com/mk-fg/dspam-milter/commit/a50ae145aff38abbc413cd974e4d0ef7045faa55>),
> but it's rather trivial so should probably work.
> Would appreciate if you'd report any errors/bugs there, if you'll end up
> trying the thing out.

Need your advice again. Here is what I did and the results I got.

Did a manual test first to make sure dspamc is working.

cat 
1484937696.M989803P20777.prometheus.mindmedia.com.sg,S=34124,W=34717:2, 
| dspamc --user anthony@mindmedia.com.sg --deliver=summary

X-DSPAM-Result: anthony@mindmedia.com.sg; result="Spam"; class="Spam"; 
probability=1.0000; confidence=0.76; signature=2,588280b5297056452515525

So the dspamc is working with my config of dspam server.

Here comes the problem. Here is my postfix main.cf setting.

# setup milters for opendkim and dspam
smtpd_milters = inet:127.0.0.1:8891, unix:/tmp/dspam_milter.sock
non_smtpd_milters = $smtpd_milters
milter_default_action = accept

When using dspam-milter I get the following error in postfix log.

Jan 21 05:33:04 prometheus postfix/smtpd[32006]: warning: milter 
unix:/tmp/dspam_milter.sock: can't read SMFIC_OPTNEG reply packet 
header: Success
Jan 21 05:33:04 prometheus postfix/smtpd[32006]: warning: milter 
unix:/tmp/dspam_milter.sock: read error in initial handshake

This error from dspam-milter.

[root@prometheus postfix]# /etc/init.d/dspam-milter start
Starting dspam-milter: DEBUG :: Starting libmilter loop...
Traceback (most recent call last):
    File "/usr/lib64/python2.6/site-packages/Milter/__init__.py", line 
653, in negotiate_callback
      m = factory()
    File "/usr/local/dspam-milter/dspam-milter.py", line 51, in __init__
      self._log = MilterLogFilter.getLogger(Milter.uniqueID())
    File "/usr/local/dspam-milter/dspam-milter.py", line 20, in getLogger
      milter_id = cls.milter_id_format.format(milter_id)
ValueError: zero length field name in format

Here are the values of /tmp/dspam_milter.sock

srwxrwx--- 1 dspam mail 0 Jan 21 05:31 dspam_milter.sock

I hope you can share with me, what I am doing wrong.

P.V.Anthony

**Comment by mk-fg** [comment]
> This error from dspam-milter.
...
>  milter_id = cls.milter_id_format.format(milter_id)
> ValueError: zero length field name in format
...
> I hope you can share with me, what I am doing wrong.

From that error, I think the answer is "running it under Python-2.6".
You should be able to check by simply running "python2" and see the version output on the first line.

`milter_id_format = '{:04d}'` format should only give that error there, where only `{0:04d}` and such were acceptable.
Even though I wrote the thing a few years ago, didn't have 2.6 anywhere back then for years, as 2.7 came out way back in 2010.

I might not remember all the quirks of 2.6 vs 2.7, but looking at the code, I suspect that this minor "`{0}` vs `{}`" formatting issue is the only incompatibility, so tried to fix that in 638440c (only used in a few places), maybe try the updated version.
As you can probably see from the script, pretty much all the code there runs for every email processed, so I think it's likely that if it works fine for one, there will be no other incompatibilities popping-up later.

Other fix, of course, is to run it with python-2.7.
If you have it installed alongside 2.6, just have 2.6 symlinked to "python2", maybe simply change shebang line on top of the script to `#!/usr/local/bin/python2.7` or such.
Note that you'll need pymilter module installed for python2.7, as different-version pythons don't usually share their "site-packages" dir (unless PYTHONPATH env-var is used, or something like that).

Fairly confident that it's an issue due to 2.6 because of that fairly unique `ValueError: zero length field name in format` error - iirc 2.5 didn't have str.format() at all and 2.7+ all allow `{}`.

**Comment by pvanthony** [comment]
On 22/01/2017 03:02, Mike Kazantsev wrote:

> Fairly confident that it's an issue due to 2.6 because of that fairly
> unique |ValueError: zero length field name in format| error - iirc 2.5
> didn't have str.format() at all and 2.7+ all allow |{}|.

You are completely correct! I was using python version 2.6.

With the changes you have done. It is working.

I am using dspam with pgsql. So far it is very good. Does not seem to 
take much cpu.

I am using mode toe and getting about 97% catch. I can share the 
dspam.config if needed.

Now it is my part to configure dspamc. Originally I was using dspam and 
all the settings was done in the dspam.conf file.

The settings done was to have the [SPAM] tagged in the subject and the 
signature in the body of the email too. Plus with the uid in the 
signature like so !DSPAM:12,586f1ff3128691876511157!. Which helps in the 
retraining with just a simple spam@example.com and notspam@example.com. 
No need for notspam+name@example.com and so on.

Some how with dspamc, it does not work like that. I have to go back to 
the docs to see how to get dspamc to work like dspam.

Thank you very much for helping me with dspam-milter. I like your 
thinking of making it simple and to use dspamc.

I always wanted to use dspam using dspamc and keeping it simple.

For now I will have to ask dspam forum on how to setup dspamc to listen 
to the dspam.conf.

Once again thank you very much for helping. Especially since you are not 
using it anymore.

P.V.Anthony

**Comment by mk-fg** [comment]
> The settings done was to have the [SPAM] tagged in the subject and the signature in the body of the email too.

Unless I'm misunderstainding something, afraid this script doesn't work like that at all.

Milter can definitely modify headers or body, but this particular script only runs `dspamc --deliver=summary ...` on an email, which prints single `X-DSPAM-Result: ...` header-line, which script then adds to email's headers, as is also written on the first lines of the README.

I.e. it never allows dspam to do anything with email, except provide that one verdict line.
And this is very intentional - I never wanted to allow dspam to edit email as it pleases (and e.g. mangle/loose it on any bugs/crashes), only provide that one header (essentially yes/no flag) to filter stuff by.

But you can probably filter stuff by X-DSPAM-Result instead of mangled "Subject:", and it also contains signature, i.e. should look something like this:

    X-DSPAM-Result: dspam; result="Innocent";
      class="Whitelisted"; probability=0.0000; confidence=1.00; signature=...

So again, only place where email is changed in this script is this one line - https://github.com/mk-fg/dspam-milter/blob/638440c/dspam-milter.py#L189 - where single header from `dspamc --deliver=summary` gets added, simple as that.


>  For now I will have to ask dspam forum on how to setup dspamc to listen to the dspam.conf.

As mentioned, unless I'm misunderstanding something above, it's not an issue with dspam at all, but just how this script works by design.


> I am using dspam with pgsql. So far it is very good. Does not seem to take much cpu.

Should've said "i/o" there instead of "cpu" - typo.

And yeah, in my case it was running on a very modest miniITX atom board, 1G RAM and old hdd, so was probably just my issue, not to mention that dspam might've improved greatly since then.

Though if you're just starting using/training dspam, it should definitely be blazing-fast of course, as it only accumulates large amount of data over time.

**Comment by mk-fg** [comment]
> single header from dspamc --deliver=summary gets added, simple as that.

Also note that if dspamc command returns anything other than "X-DSPAM-Result: ..." header/line, TEMPFAIL result will be returned to postfix, resulting in later delivery retries.
https://github.com/mk-fg/dspam-milter/blob/638440c/dspam-milter.py#L183-L185

Wanted to point it out in case you might be adding any custom options via --dspam-opts that might change that behavior.

**Comment by pvanthony** [comment]
Just sharing.
I am trying out rspamd from rspamd.com. 
It is really cool stuff. Very good results. Much more features than dspam.
Really worth a look.
Milter is builtin by the way.
